### ISSUE TITLE
OpenFHE-HEXL Build Error 

### ISSUE THREAD

**Issue by joserochh** [openfheorg/openfhe-hexl#6]
OpenFHE development not able to find HEXL headers when running scripts/build-openfhe-development-hexl.sh on Ubuntu 20.04

Example error:

In file included from /home/joserochh/openfhe-configurator/openfhe-staging/openfhe-development/src/core/include/lattice/hal/hexl/lat-backend-hexl.h:39,
                 from /home/joserochh/openfhe-configurator/openfhe-staging/openfhe-development/src/core/include/lattice/lat-hal.h:40,
                 from /home/joserochh/openfhe-configurator/openfhe-staging/openfhe-development/src/core/lib/lattice/be2-poly-impl.cpp:36:
/home/joserochh/openfhe-configurator/openfhe-staging/openfhe-development/src/core/include/lattice/hal/hexl/hexldcrtpoly.h:47:10: fatal error: hexl/hexl.hpp: No such file or directory
   47 | #include "hexl/hexl.hpp"
      |          ^~~~~~~~~~~~~~~
compilation terminated.

**Comment by jbates-duality** [comment]
This was closed shortly after report.  Officially closing now.
